//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_WebAPI_EF.Codes.Dao.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABL2
    {
        public TABL2()
        {
            this.TABL1 = new HashSet<TABL1>();
        }
    
        public int A { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
    
        public virtual ICollection<TABL1> TABL1 { get; set; }
    }
}
