//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_WebAPI_EF.Codes.Dao.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABL1
    {
        public int A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public int AX { get; set; }
    
        public virtual TABL2 TABL2 { get; set; }
    }
}
